#!/usr/bin/env python
import os #For pids
from subprocess import call #For making shell command calls
import sys #Cmd line args

#Get list of running pids
#Thanks http://stackoverflow.com/questions/2703640/process-list-on-linux-via-python
pids= [pid for pid in os.listdir('/proc') if pid.isdigit()]
for pid in pids:
    #Give process path
    #print open(os.path.join('/proc', pid, 'cmdline'), 'rb').read()
    cmd = []
    cmd.append("renice")
    #First arg should be nice value
    cmd.append(str(sys.argv[1]))
    cmd.append("-p")
    cmd.append(str(pid))
    #print cmd
    call(cmd)

